# Generated by Django 5.0.7 on 2024-07-29 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_post_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="following_list",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
